interface AltairSignatureBadgeProps {
  label?: string
  className?: string
}

export default function AltairSignatureBadge({
  label = 'Generated by ALTAIR',
  className = '',
}: AltairSignatureBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border border-blue-400/20 bg-blue-950/35 px-2.5 py-1 text-[10px] font-medium tracking-wide text-blue-200/75 sm:text-[11px] ${className}`}
    >
      <span className="text-blue-300/80" aria-hidden="true">
        ✦
      </span>
      {label}
    </span>
  )
}
