import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from 'docx'
import type { RoadmapData } from '../types/roadmap'
import { buildRoadmapExportSections } from './roadmapExportContent'
import { buildRoadmapFilename, downloadBlob } from './downloadBlob'

function paragraph(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text })],
    spacing: { after: 160 },
  })
}

function subheading(text: string): Paragraph {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 180, after: 120 },
  })
}

function bulletItem(text: string): Paragraph {
  return new Paragraph({
    text,
    bullet: { level: 0 },
    spacing: { after: 80 },
  })
}

export async function exportRoadmapDocx(roadmap: RoadmapData): Promise<void> {
  const sections = buildRoadmapExportSections(roadmap)
  const children: Paragraph[] = [
    new Paragraph({
      text: 'ALTAIR Learning Roadmap',
      heading: HeadingLevel.TITLE,
      spacing: { after: 120 },
    }),
    paragraph(
      `${roadmap.overview.title} — Generated ${new Date(roadmap.metadata.generatedAt).toLocaleDateString()}`,
    ),
  ]

  for (const section of sections) {
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 280, after: 160 },
      }),
    )

    for (const block of section.blocks) {
      switch (block.type) {
        case 'subheading':
          children.push(subheading(block.text))
          break
        case 'paragraph':
          children.push(paragraph(block.text))
          break
        case 'keyValue':
          children.push(
            new Paragraph({
              children: [
                new TextRun({ text: `${block.label}: `, bold: true }),
                new TextRun({ text: block.value }),
              ],
              spacing: { after: 120 },
            }),
          )
          break
        case 'list':
          for (const item of block.items) {
            children.push(bulletItem(item))
          }
          break
      }
    }
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by ALTAIR — Find your way forward.',
          italics: true,
        }),
      ],
      spacing: { before: 280 },
    }),
  )

  const document = new Document({
    sections: [{ children }],
  })

  const blob = await Packer.toBlob(document)
  downloadBlob(blob, buildRoadmapFilename(roadmap.metadata.careerGoal, 'docx'))
}
